#-------------------------------
# General Site Settings
title: my-blog
logo: logo.svg # You can add own logo.
description: minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Sashini Liyanage
  image: 01.jpg
  say-hello: Hello, I’m <strong>Sashini Liyanage</strong>
  bio: Designs, talks, and writes about <strong>web</strong> and dev. I share small tips on computer engineering. Loves <a href="#">music</a> & films.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://www.facebook.com/profile.php?id=100003157635904 # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/sashinuu  # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Sashini # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: sashinuu # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
